# Periodically runs the tests on master and posts coverage results to codecov.

name: Test with coverage
on:
  workflow_dispatch: {}
  schedule:
    # Run every 12 hours.
    - cron: '0 */12 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  info:
    name: info
    uses: ./.github/workflows/ci-info.yml
    permissions:
      contents: read
    with:
      ref: master
      is-snapshot: true
    secrets: inherit

  ci:
    name: CI
    needs: [info]
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      # To sign artifacts.
      id-token: write
    with:
      ref: master
      version: ${{ needs.info.outputs.version }}
      lint: true
      build-all-targets: true
      test-codegen:  true
      test-version-sets: current
      integration-test-platforms: ubuntu-latest
      acceptance-test-platforms: macos-latest windows-latest
      enable-coverage: true
    secrets: inherit
